// Categories Array
export const categories = [
  { description: "Behavioral", isDefault: true, userId: null },
  { description: "HTML", isDefault: true, userId: null, is100Devs: true },
  {
    description: "Accessibility",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  { description: "CSS", isDefault: true, userId: null, is100Devs: true },
  {
    description: "JavaScript",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  {
    description: "Coding warm-ups",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  { description: "Async", isDefault: true, userId: null, is100Devs: true },
  { description: "Browser", isDefault: true, userId: null, is100Devs: true },
  {
    description: "Performance",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  {
    description: "TypeScript",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  { description: "React", isDefault: true, userId: null, is100Devs: true },
  { description: "Node", isDefault: true, userId: null, is100Devs: true },
  { description: "Express", isDefault: true, userId: null, is100Devs: true },
  { description: "APIs", isDefault: true, userId: null, is100Devs: true },
  { description: "Databases", isDefault: true, userId: null, is100Devs: true },
  { description: "Auth", isDefault: true, userId: null, is100Devs: true },
  { description: "Security", isDefault: true, userId: null, is100Devs: true },
  {
    description: "Networking",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  { description: "HTTP", isDefault: true, userId: null, is100Devs: true },
  {
    description: "Deployment",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  { description: "Testing", isDefault: true, userId: null, is100Devs: true },
  { description: "Debugging", isDefault: true, userId: null, is100Devs: true },
  { description: "Git", isDefault: true, userId: null, is100Devs: true },
  { description: "Workflow", isDefault: true, userId: null, is100Devs: true },
  {
    description: "AI-Assisted Engineering",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
  { description: "CS Theory", isDefault: true, userId: null, is100Devs: true },
  {
    description: "Data Structures",
    isDefault: true,
    userId: null,
    is100Devs: true,
  },
];
